### ISSUE TITLE
Exception in log when using single config file

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#121]
Exception:

```
java.lang.NullPointerException: null
	at biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl.persistInstalledConfigurations(AcHistoryServiceImpl.java:163)
	at biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl.persistHistory(AcHistoryServiceImpl.java:81)
	at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.installConfigurationFiles(AceServiceImpl.java:394)
	at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:317)
```

**Comment by ghenzler** [comment]
Fixed with a88f3bd
