### ISSUE TITLE
Group definition without path fails with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Netcentric/accesscontroltool#128]
If "path" is not set for a group then it cannot be created. Version 1.9.1.

`- group_config:

```
- my-group:

    - name:
```

`

`Caused by: org.apache.jackrabbit.vault.packaging.PackageException: String index out of range: 0
    at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.execute(AcToolInstallHook.java:66)
    at com.day.jcr.vault.packaging.impl.JrVltInstallHookAdapter.execute(JrVltInstallHookAdapter.java:42)
    ... 71 common frames omitted
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:646)
    at org.apache.jackrabbit.oak.security.user.UserProvider.getFolderPath(UserProvider.java:329)
    at org.apache.jackrabbit.oak.security.user.UserProvider.createFolderNodes(UserProvider.java:294)
    at org.apache.jackrabbit.oak.security.user.UserProvider.createAuthorizableNode(UserProvider.java:257)
    at org.apache.jackrabbit.oak.security.user.UserProvider.createGroup(UserProvider.java:190)
    at org.apache.jackrabbit.oak.security.user.UserManagerImpl.createGroup(UserManagerImpl.java:210)
    at org.apache.jackrabbit.oak.security.user.UserManagerImpl.createGroup(UserManagerImpl.java:199)
    at org.apache.jackrabbit.oak.jcr.delegate.UserManagerDelegator$12.perform(UserManagerDelegator.java:212)
    at org.apache.jackrabbit.oak.jcr.delegate.UserManagerDelegator$12.perform(UserManagerDelegator.java:208)
    at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:200)
    at org.apache.jackrabbit.oak.jcr.delegate.UserManagerDelegator.createGroup(UserManagerDelegator.java:208)
    at biz.netcentric.cq.tools.actool.authorizableutils.impl.AuthorizableCreatorServiceImpl.createNewGroup(AuthorizableCreatorServiceImpl.java:495)
`

**Comment by j--wong** [comment]
Yep, I am having the same issue even though `path` is an optional parameter as described here https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md#configuration-of-groups

Currently, I am setting `path` to a relative value to workaround this error.
