### ISSUE TITLE
ACTool fails when using "initialContent"

### ISSUE THREAD

**Issue by inedoviesov1** [Netcentric/accesscontroltool#198]
When using "initialContent" and setting permissions with the following config:
```
        - path: /etc/tags/newtags
          permission: allow
          actions: read
          initialContent: |
                            <jcr:root jcr:primaryType="cq:Tag"
                                jcr:title="New Tags"
                                sling:resourceType="cq/tagging/components/tag"/>
```

ACTool fails with the following exception:
```
18.06.2017 13:49:54.017 *ERROR* [qtp1071342378-4085] biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl Exception in AceServiceImpl: {}
javax.jcr.PathNotFoundException: No tree at /etc/tags/newtags
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.getTree(AbstractAccessControlManager.java:163)
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.getPrivileges(AbstractAccessControlManager.java:215)
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.getPrivileges(AbstractAccessControlManager.java:116)
	at org.apache.jackrabbit.oak.jcr.delegate.JackrabbitAccessControlManagerDelegator$5.perform(JackrabbitAccessControlManagerDelegator.java:108)
	at org.apache.jackrabbit.oak.jcr.delegate.JackrabbitAccessControlManagerDelegator$5.perform(JackrabbitAccessControlManagerDelegator.java:104)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:208)
	at org.apache.jackrabbit.oak.jcr.delegate.JackrabbitAccessControlManagerDelegator.getPrivileges(JackrabbitAccessControlManagerDelegator.java:104)
	at com.day.cq.security.util.CqActions.getPrivileges(CqActions.java:386)
	at com.day.cq.security.util.CqActions.getAllowedActions(CqActions.java:202)
	at biz.netcentric.cq.tools.actool.aceinstaller.AceBeanInstallerIncremental.applyCqActions(AceBeanInstallerIncremental.java:351)
	at biz.netcentric.cq.tools.actool.aceinstaller.AceBeanInstallerIncremental.getPrincipalAceBeansForActionAceBean(AceBeanInstallerIncremental.java:280)
	at biz.netcentric.cq.tools.actool.aceinstaller.AceBeanInstallerIncremental.getPrincipalAceBeansForActionAceBeanCached(AceBeanInstallerIncremental.java:260)
	at biz.netcentric.cq.tools.actool.aceinstaller.AceBeanInstallerIncremental.transformActionsIntoPrivileges(AceBeanInstallerIncremental.java:224)
	at biz.netcentric.cq.tools.actool.aceinstaller.AceBeanInstallerIncremental.installAcl(AceBeanInstallerIncremental.java:80)
	at biz.netcentric.cq.tools.actool.aceinstaller.BaseAceBeanInstaller.installPathBasedACEs(BaseAceBeanInstaller.java:89)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAces(AcInstallationServiceImpl.java:382)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAcConfiguration(AcInstallationServiceImpl.java:242)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installMergedConfigurations(AcInstallationServiceImpl.java:520)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:205)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.apply(AcInstallationServiceImpl.java:161)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.apply(AcInstallationServiceImpl.java:139)
	at biz.netcentric.cq.tools.actool.jmx.AceServiceMBeanImpl.apply(AceServiceMBeanImpl.java:58)
```

It happens because new session is being created and initial content, which has been created in old session, is not visible.
Issue occurs after this commit https://github.com/Netcentric/accesscontroltool/pull/192/commits/13be6b34ecabfdd4d3a22406bc59ccfdcc547400

**Comment by ghenzler** [comment]
@inedoviesov1 The easiest workaround for this should be to use a privilege (`privilege: jcr:read`) instead of an action for this particular ACE. Another option would be to use the 1.x style, non-incremental update that can be enabled with the following config: 

```
- global_config
        installAclsIncrementally: false
```
