### ISSUE TITLE
AC Tool Healthcheck should be more resilient

### ISSUE THREAD

**Issue by joerghoh** [Netcentric/accesscontroltool#218]
The LastRunHealthSuccessCheck reads the last status of the run from the repository.
But if storing the history fails (like with the exception below), the healthcheck reports inaccurate data: it does not report the failing of persisting the history, but rather reports the status of the run before the last run.

This should be changed in a way, that the result of the last run should not be read from the repository, but rather be retrieved in-memory from the other AC services, which are aware of success or failures.

Otherwise this healthcheck is rather useless to me.

```
23.08.2017 08:34:53.424 *ERROR* [OsgiInstallerImpl-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl RepositoryException:
javax.jcr.InvalidItemStateException: OakState0001: Unresolved conflicts in /var/statistics/achistory
                at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:237)
                at org.apache.jackrabbit.oak.api.CommitFailedException.asRepositoryException(CommitFailedException.java:212)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.newRepositoryException(SessionDelegate.java:661)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:487)
                at org.apache.jackrabbit.oak.jcr.session.SessionImpl$8.performVoid(SessionImpl.java:424)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.performVoid(SessionDelegate.java:266)
                at org.apache.jackrabbit.oak.jcr.session.SessionImpl.save(SessionImpl.java:421)
                at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:497)
                at org.apache.sling.jcr.base.SessionProxyHandler$SessionProxyInvocationHandler.invoke(SessionProxyHandler.java:113)
                at com.sun.proxy.$Proxy12.save(Unknown Source)
                at biz.netcentric.cq.tools.actool.installationhistory.impl.AcHistoryServiceImpl.persistHistory(AcHistoryServiceImpl.java:91)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.installConfigurationFiles(AceServiceImpl.java:209)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:134)
                at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:118)
                at com.db.cecm.startup.StartupCheckServlet.activate(StartupCheckServlet.java:48)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
…
Caused by: org.apache.jackrabbit.oak.api.CommitFailedException: OakState0001: Unresolved conflicts in /var/statistics/achistory
                at org.apache.jackrabbit.oak.plugins.commit.ConflictValidator.failOnMergeConflict(ConflictValidator.java:115)
                at org.apache.jackrabbit.oak.plugins.commit.ConflictValidator.propertyAdded(ConflictValidator.java:84)
                at org.apache.jackrabbit.oak.spi.commit.CompositeEditor.propertyAdded(CompositeEditor.java:83)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.propertyAdded(EditorDiff.java:82)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:378)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:399)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:399)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.childNodeChanged(EditorDiff.java:148)
                at org.apache.jackrabbit.oak.plugins.memory.ModifiedNodeState.compareAgainstBaseState(ModifiedNodeState.java:399)
                at org.apache.jackrabbit.oak.spi.commit.EditorDiff.process(EditorDiff.java:52)
                at org.apache.jackrabbit.oak.spi.commit.EditorHook.processCommit(EditorHook.java:54)
                at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
                at org.apache.jackrabbit.oak.spi.commit.CompositeHook.processCommit(CompositeHook.java:61)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreBranch$InMemory.merge(DocumentNodeStoreBranch.java:543)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreBranch.merge0(DocumentNodeStoreBranch.java:223)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreBranch.merge(DocumentNodeStoreBranch.java:171)
                at org.apache.jackrabbit.oak.plugins.document.DocumentRootBuilder.merge(DocumentRootBuilder.java:158)
                at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore.merge(DocumentNodeStore.java:1497)
                at org.apache.jackrabbit.oak.core.MutableRoot.commit(MutableRoot.java:247)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.commit(SessionDelegate.java:339)
                at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.save(SessionDelegate.java:485)
                ... 92 common frames omitted
 ```

**Comment by ghenzler** [comment]
Reading the history from the repo has the advantage that it remains available after a restart. Maybe a combination of the "repo history" and the runtime state (AcHistoryServiceImpl.persistHistory() could hold a flag that the history could not be persisted) would be the best for the HC.
