### ISSUE TITLE
Fails to install group and set permissions in one step

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Netcentric/accesscontroltool#23]
Example config:

- group_config:

    - system-tags:

       - name: 
         isMemberOf:
         members:
         path: m

- ace_config:

    - system-tags:

       - path: /etc/tags
         permission: allow
         actions: read
         privileges: 

Leads to:

2015-08-06 10:01:14.23:  start merging configuration data from: /apps/mwsg-system/acl/serviceuser/config
2015-08-06 10:01:14.232:  start installation of merged configurations
2015-08-06 10:01:14.998:  finished installation of groups configuration without errors!
2015-08-06 10:01:15.003: EXCEPTION: java.util.NoSuchElementException
2015-08-06 10:01:15.003:  performing authorizable installation rollback(s)
2015-08-06 10:01:15.003: WARNING: starting rollback of authorizables...
2015-08-06 10:01:15.003: WARNING: performing Groups rollback!
2015-08-06 10:01:15.036: WARNING: removed authorizable system-tags from the system!
2015-08-06 10:01:15.039:  saved history in node: /var/statistics/achistory/history_1438848075038

06.08.2015 10:01:14.995 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.authorizableutils.impl.AuthorizableCreatorServiceImpl Successfully created new Group: system-tags
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl finished installation of groups configuration without errors!
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl --- start installation of access control configuration ---
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.helper.AcHelper Paths in merged config = [/etc/tags]
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.helper.AcHelper authorizablesInAclFromConfig: [system-tags]
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.helper.AcHelper Added following ACE to the merged ACL: AceBean [jcrPath=/etc/tags
, permission=allow
, repGlob=null
, actionsString=null
, privilegesString=jcr:read
, principal=mwsg-system-tags
, actions=[read]]
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.helper.AcHelper Added following ACE to the merged ACL: AceBean [jcrPath=/etc/tags
, permission=allow
, repGlob=null
, actionsString=null
, privilegesString=crx:replicate,jcr:versionManagement,jcr:read,jcr:modifyAccessControl,jcr:readAccessControl,rep:write,jcr:lockManagement
, principal=tag-administrators
, actions=[modify, replicate, read, create, delete, acl_read, acl_edit]]
06.08.2015 10:01:14.998 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.helper.AcHelper Added following ACE to the merged ACL: AceBean [jcrPath=/etc/tags
, permission=allow
, repGlob=
, actionsString=null
, privilegesString=jcr:read
, principal=everyone
, actions=[read]]
06.08.2015 10:01:15.000 *INFO* [qtp1190515388-521] biz.netcentric.cq.tools.actool.helper.AcHelper Removed all policies from node /etc/tags.

06.08.2015 10:01:15.003 *ERROR* [qtp1190515388-521] biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl Exception in AceServiceImpl: {}
java.util.NoSuchElementException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1205)
	at java.util.TreeMap$KeyIterator.next(TreeMap.java:1261)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.getPrincipalbyQuery(AcHelper.java:291)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.getLdapImportGroupPrincipal(AcHelper.java:266)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.resetAclInRepository(AcHelper.java:189)
	at biz.netcentric.cq.tools.actool.helper.AcHelper.installPathBasedACEs(AcHelper.java:147)
	at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.installAces(AceServiceImpl.java:151)
	at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.installConfigurationFromYamlList(AceServiceImpl.java:129)
	at biz.netcentric.cq.tools.actool.aceservice.impl.AceServiceImpl.execute(AceServiceImpl.java:253)
	at biz.netcentric.cq.tools.actool.aceservicejmx.impl.AceServiceMBeanImpl.execute(AceServiceMBeanImpl.java:57)

**Comment by kwin** [comment]
Actually we should further debug this. Which `NodeIterator` is used there? Why is it returning `true` for `hasNext` but throws a NPE for `nextNode()`. What would happen if we call `next()` on that iterator instead?
