### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.LinkedHashMap

### ISSUE THREAD

**Issue by singd12** [Netcentric/accesscontroltool#294]
Hi 

I am getting below issue while running my YAML files. Not sure how i can debug my YAML script to get into root cause. 
Any urgent help really appreciate.

##############################################################################

14:15:20.054: EXCEPTION: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.LinkedHashMap
14:15:20.057:  Saved history in node: /var/statistics/achistory/history_1527135320055_via_api

Execution time: 0ms

Success: false
##############################################################################

AND backend log files 

24.05.2018 14:56:45.038 *ERROR* [qtp152277884-3175] biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl Exception in AceServiceImpl: {}
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.LinkedHashMap
        at biz.netcentric.cq.tools.actool.configreader.YamlConfigurationMerger.getMergedConfigurations(YamlConfigurationMerger.java:101)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:201)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.apply(AcInstallationServiceImpl.java:161)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.apply(AcInstallationServiceImpl.java:139)
        at biz.netcentric.cq.tools.actool.jmx.AceServiceMBeanImpl.apply(AceServiceMBeanImpl.java:58)
        at sun.reflect.GeneratedMethodAccessor149.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at sun.reflect.misc.Trampoline.invoke(Unknown Source)

**Comment by ghenzler** [comment]
@singd12 without the yaml file itself it is hard to tell - the easiest to debug it yourself is to remove some parts of the config in CRXDE until it works (or you start with minimal config and add the actual config step by step to find out where the problem lies)

**Comment by kwin** [comment]
I am closing this, as there was no further information provided in this ticket.
