### ISSUE TITLE
Issue when setting ACEs to unmanaged users

### ISSUE THREAD

**Issue by tnebe** [Netcentric/accesscontroltool#320]
With latest ACTool 2.1.1 we are facing issues in applying ACE´s to users that are not managed by the ACTool  even if `defaultUnmanagedExternalMembersRegex` has been set.

Example:

```

- global_config:
    defaultUnmanagedExternalMembersRegex: .*

- group_config: 
  - fragment-version-manager-service: 
    - description: Group to which ACTool managed ACEs are bound which belong to the system user version-manager-service
      members: version-manager-service
      unmanagedExternalMembersRegex: .* # does not fix the issue as well
      path: /home/groups/fragments

- ace_config: 
  - fragment-version-manager-service: 
    - path: /conf
      permission: allow
      privileges: rep:write,jcr:versionManagement

```

When trying to apply, the following error appears

```
09.10.2018 17:35:09.422 *WARN* [qtp1850450949-6313] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook actool threw package exception. Prepare aborted.
org.apache.jackrabbit.vault.packaging.PackageException: Group 'fragment-version-manager-service' references external group group or user 'version-manager-service' via members but relationships to this external group is explicitly unmanged by regex .*
        at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.execute(AcToolInstallHook.java:68)
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.execute(InstallHookProcessorImpl.java:148)
        at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:227)
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:398)
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:357)
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:351)
        at com.day.crx.packmgr.impl.servlets.ServiceServlet.doInstall(ServiceServlet.java:421)
        at com.day.crx.packmgr.impl.servlets.ServiceServlet.upload(ServiceServlet.java:496)
        at com.day.crx.packmgr.impl.servlets.ServiceServlet.doService(ServiceServlet.java:174)
        at com.day.crx.packmgr.impl.AbstractServlet.service(AbstractServlet.java:54)
        at com.day.crx.packmgr.impl.MainServlet.doService(MainServlet.java:157)
        at com.day.crx.packmgr.impl.MainServlet.service(MainServlet.java:134)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:85)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:79)
        at com.adobe.granite.cors.impl.CORSHandler.doFilter(CORSHandler.java:118)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
        at com.adobe.granite.license.impl.LicenseCheckFilter.doFilter(LicenseCheckFilter.java:308)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
        at org.apache.felix.http.sslfilter.internal.SslFilter.doFilter(SslFilter.java:96)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
        at org.apache.sling.security.impl.ReferrerFilter.doFilter(ReferrerFilter.java:295)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
        at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:138)
        at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:135)
        at org.apache.felix.http.base.internal.dispatch.InvocationChain.doFilter(InvocationChain.java:74)
        at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:127)
        at org.apache.felix.http.base.internal.dispatch.DispatcherServlet.service(DispatcherServlet.java:49)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:499)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Group 'fragment-version-manager-service' references external group group or user 'version-manager-service' via members but relationships to this external group is explicitly unmanged by regex .*
        at biz.netcentric.cq.tools.actool.validators.UnmangedExternalMemberRelationshipChecker.checkMembers(UnmangedExternalMemberRelationshipChecker.java:69)
        at biz.netcentric.cq.tools.actool.validators.UnmangedExternalMemberRelationshipChecker.validate(UnmangedExternalMemberRelationshipChecker.java:25)
        at biz.netcentric.cq.tools.actool.configreader.YamlConfigurationMerger.getMergedConfigurations(YamlConfigurationMerger.java:190)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:207)
        at biz.netcentric.cq.tools.actool.installhook.impl.AcToolInstallHookServiceImpl.installYamlFilesFromPackage(AcToolInstallHookServiceImpl.java:44)
        at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.execute(AcToolInstallHook.java:61)
        ... 48 common frames omitted
```

Might be caused by changes done in https://github.com/Netcentric/accesscontroltool/commit/333f62c5c841fa1a35d7da0d87323081e1b46b52

**Comment by kwin** [comment]
There is both a typo in the error message "Group 'fragment-version-manager-service' references external group group or user 'version-manager-service' via members but relationships to this external group is explicitly unmanged by regex .*" as well as in the class name: {{unmanged}} instead of {{unmanaged}}. Also in this case the validation seems to emit a false positive. @ghenzler WDYT?

**Comment by ghenzler** [comment]
@tnebe I suppose you **do want to manage** the relationship between `fragment-version-manager-service` and `version-manager-service`, hence both `defaultUnmanagedExternalMembersRegex` and `unmanagedExternalMembersRegex` can be removed. 

Just tested the following and it works:

```
- group_config: 
  - fragment-version-manager-service: 
    - description: Group to which ACTool managed ACEs are bound which belong to the system user version-manager-service
      members: version-manager-service
      path: /home/groups/fragments

- ace_config: 
  - fragment-version-manager-service: 
    - path: /conf
      permission: allow
      privileges: rep:write,jcr:versionManagement
```

If you now take out the `version-manager-service` from `members` of `fragment-version-manager-service` the relationship is removed => correctly managed by AC Tool. There are other reasons to not manage relationships, but not this example it does not make sense. However, if you wanted to work without the fragment `fragment-version-manager-service`, you could take `version-manager-service` itself into the managed groups of the AC Tool and adjusting it directly: 

```
- user_config: 
  - version-manager-service: 
    - path: /home/users/system/wcm
      # the user does exist already, make sure the path is set correctly
      isSystemUser: true
      # everything outside /conf is not be managed by the ac tool
      unmanagedAcePathsRegex: /(?!conf).*

- ace_config: 
  - version-manager-service: 
    - path: /conf
      permission: allow
      privileges: rep:write,jcr:versionManagement
```

**Comment by tnebe** [comment]
Hi @ghenzler, thanks for the reply and indeed does removing both `defaultUnmanagedExternalMembersRegex ` and `unmanagedExternalMembersRegex` solve this issue. AC Tool runs w/o any error and the fragment group is assigned correctly to `version-manager-service` whereas I am not sure if setting `defaultUnmanagedExternalMembersRegex: .*` should prevent assigning AC Tool managed groups to external (AEM-owned) users/ groups.

From https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md this might be a different aspect then!?

> defaultUnmanagedExternalMembersRegex: .* allow arbitrary groups to inherit from ACTool managed groups and keep those (unmanaged) relations even though relationship hasn't been established through the ACTool. Might be useful in a multi-tenant setup where each tenant maintains his own list of groups (e.g. via ACTool in dedicated packages) and wants to inherit from some fragments being set up by the global YAML file.

The same setup, w/o inline `unmanagedExternalMembersRegex: .*`, was working with AC Tool v.2.0.6 before.

**Comment by ghenzler** [comment]
Since #244 we have a consistent approach for what is added/removed by AC Tool (since then only things are added that are then also removed), before that certain relationships would have been added even if they are declared as unmanaged using  `unmanagedExternalMembersRegex`. See https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-unmanaged-aspects for details.

**Comment by tnebe** [comment]
Ok, thank you!
