### ISSUE TITLE
Unsupported operation exception / traversing too many nodes

### ISSUE THREAD

**Issue by pun-ky** [Netcentric/accesscontroltool#466]
I've got some ACL Yaml files, on author instance package installation & ACL application works properly, however on publish:

```
25.06.2020 12:29:15.217 *INFO* [qtp470401984-64-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.HistoryUtils Saved history in node: /var/statistics/achistory/history_1593088155216_via_fooproject.ui.acl-0.190.0-SNAPSHOT
25.06.2020 12:29:15.229 *ERROR* [qtp470401984-64] biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook Exception during execution of install hook: java.lang.UnsupportedOperationException: The query read or traversed more than 100000 nodes. To avoid affecting other tasks, processing was stopped.
java.lang.UnsupportedOperationException: The query read or traversed more than 100000 nodes. To avoid affecting other tasks, processing was stopped.
	at org.apache.jackrabbit.oak.query.FilterIterators.checkReadLimit(FilterIterators.java:70) [org.apache.jackrabbit.oak-core:1.10.3]
	at org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor.fetchNext(Cursors.java:341) [org.apache.jackrabbit.oak-core:1.10.3]
	at org.apache.jackrabbit.oak.plugins.index.Cursors$TraversingCursor.next(Cursors.java:320) [org.apache.jackrabbit.oak-core:1.10.3]
	at org.apache.jackrabbit.oak.query.ast.SelectorImpl.next(SelectorImpl.java:437) [org.apache.jackrabbit.oak-core:1.10.3]
	at org.apache.jackrabbit.oak.query.QueryImpl$RowIterator.fetchNext(QueryImpl.java:829) [org.apache.jackrabbit.oak-core:1.10.3]
	at org.apache.jackrabbit.oak.query.QueryImpl$RowIterator.hasNext(QueryImpl.java:856) [org.apache.jackrabbit.oak-core:1.10.3]
	at org.apache.jackrabbit.oak.jcr.query.QueryResultImpl$4.fetch(QueryResultImpl.java:186) [org.apache.jackrabbit.oak-jcr:1.10.3]
	at org.apache.jackrabbit.oak.jcr.query.QueryResultImpl$4.next(QueryResultImpl.java:212) [org.apache.jackrabbit.oak-jcr:1.10.3]
	at org.apache.jackrabbit.oak.jcr.query.QueryResultImpl$4.next(QueryResultImpl.java:175) [org.apache.jackrabbit.oak-jcr:1.10.3]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate$SynchronizedIterator.next(SessionDelegate.java:702) [org.apache.jackrabbit.oak-jcr:1.10.3]
	at org.apache.jackrabbit.oak.jcr.query.PrefetchIterator.next(PrefetchIterator.java:88) [org.apache.jackrabbit.oak-jcr:1.10.3]
	at org.apache.jackrabbit.commons.iterator.RangeIteratorAdapter.next(RangeIteratorAdapter.java:152) [org.apache.jackrabbit.jackrabbit-jcr-commons:2.18.2]
	at org.apache.jackrabbit.commons.iterator.RangeIteratorDecorator.next(RangeIteratorDecorator.java:92) [org.apache.jackrabbit.jackrabbit-jcr-commons:2.18.2]
	at org.apache.jackrabbit.commons.iterator.NodeIteratorAdapter.nextNode(NodeIteratorAdapter.java:80) [org.apache.jackrabbit.jackrabbit-jcr-commons:2.18.2]
	at biz.netcentric.cq.tools.actool.helper.QueryHelper.getNodes(QueryHelper.java:130) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.helper.QueryHelper.getRepPolicyNodes(QueryHelper.java:96) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.dumpservice.impl.DumpServiceImpl.getACLDumpBeans(DumpServiceImpl.java:351) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.dumpservice.impl.DumpServiceImpl.createAclDumpMap(DumpServiceImpl.java:409) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installMergedConfigurations(AcInstallationServiceImpl.java:589) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:232) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.installhook.impl.AcToolInstallHookServiceImpl.installYamlFilesFromPackage(AcToolInstallHookServiceImpl.java:43) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.execute(AcToolInstallHook.java:63) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.3.2]
	at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.execute(InstallHookProcessorImpl.java:149) [org.apache.jackrabbit.vault:3.2.8]
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:227) [org.apache.jackrabbit.vault:3.2.8]
```

missing index or sth like that? any suggestions?

**Comment by pun-ky** [comment]
@kwin how this commit c7dd1ca will fix issue?

**Comment by kwin** [comment]
https://github.com/Netcentric/accesscontroltool/commit/c7dd1ca36b3d102ae483f5d3a94c0bfb85d3d622 was just committed with the wrong message. It will not fix it. Regarding your issue please have a look at https://github.com/Netcentric/accesscontroltool/blob/develop/README.md#oak-index-for-repacl.

**Comment by kwin** [comment]
#386 is related

**Comment by ghenzler** [comment]
@pun-ky Your stack trace points to version 2.3.2 of the AC tool - issue #386 (allowing to work without extra oak index for `rep:ACL` by querying for `rep:ACE` that has an ootb index) was only fixed with v2.4.1. 

So for you setup the AC Tool tries to query `rep:ACL` nodes and you have more than 100,000 in the system. The easiest is just to increase the configuration for the read limits if you are allowed to do so. Overall you probably have more ACLs on the system that you should have, it's probably worth a more detailed analysis.

See also 
https://issues.apache.org/jira/browse/OAK-6875 (introduced read limits also for queries for indexes)
https://issues.apache.org/jira/browse/OAK-5291 (this would allow the AC Tool to specify the read limit per query, exactly what we need)

**Comment by ghenzler** [comment]
@pun-ky Please re-open if you would like to suggest a change on AC tool side

**Comment by pun-ky** [comment]
@ghenzler mistake on my side. No indexes pkg on publish for some strange reason. Thanks.
