### ISSUE TITLE
AEMaaCS: ClassNotFoundException for AcToolInstallHook during local install using archetype version 24

### ISSUE THREAD

**Issue by aderler** [Netcentric/accesscontroltool#529]
When installing AcTool in a project based on the AEM cloud archetype version 24 within a single package (autoInstallSinglePackage), the execution of the install hook triggers a ClassNotFoundException for the class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook. 

Stacktrace:
> 16.12.2020 09:27:32.134 *ERROR* [OsgiInstallerImpl] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Error while initializing hook: org.apache.jackrabbit.vault.packaging.PackageException: hook's main class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook not found: actool
16.12.2020 09:27:32.135 *ERROR* [OsgiInstallerImpl] com.adobe.granite.installer.factory.packages.impl.PackageTransformer Error while processing install task of at.oegbverlag:accesscontrol:1.0-SNAPSHOT.
org.apache.jackrabbit.vault.packaging.PackageException: hook's main class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook not found: actool
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.init(InstallHookProcessorImpl.java:242) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.access$300(InstallHookProcessorImpl.java:162) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.initHook(InstallHookProcessorImpl.java:122) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.registerHooks(InstallHookProcessorImpl.java:96) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.prepareExtract(ZipVaultPackage.java:181) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:393) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:360) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.install(JcrPackageImpl.java:354) [org.apache.jackrabbit.vault:3.4.0]
        at com.adobe.granite.installer.factory.packages.impl.PackageTransformer$InstallPackageTask.execute(PackageTransformer.java:350) [com.adobe.granite.installer.factory.packages:1.0.18]
        at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:918) [org.apache.sling.installer.core:3.11.4]
        at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:755) [org.apache.sling.installer.core:3.11.4]
        at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:304) [org.apache.sling.installer.core:3.11.4]
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Class not found biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook
        at com.adobe.granite.installer.factory.packages.impl.PackageAdminClassLoader.loadClass(PackageAdminClassLoader.java:140) [com.adobe.granite.installer.factory.packages:1.0.18]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.loadMainClass(InstallHookProcessorImpl.java:250) [org.apache.jackrabbit.vault:3.4.0]
        at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl$Hook.init(InstallHookProcessorImpl.java:238) [org.apache.jackrabbit.vault:3.4.0]
        ... 12 common frames omitted

Steps to reproduce:

1. Create a fresh project using AEM maven archetype version 24
2. Add maven dependency for accesscontroltool-package to "all" and root
3. Add embedded for accesscontroltool-package to the "all" package (subPackages should not used according to docs https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html#embeddeds)

```
<embedded>
    <groupId>biz.netcentric.cq.tools.accesscontroltool</groupId>
    <artifactId>accesscontroltool-package</artifactId>
    <filter>true</filter>
    <type>zip</type>
    <target>/apps/mysite-packages/application/install</target>
</embedded>
```

4. Add install hook to filevault-package-maven-plugin configuration in the "all" package

```
<properties>
  <installhook.actool.class>biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook
  </installhook.actool.class>
  <actool.atInstalledPhase>true</actool.atInstalledPhase>
</properties>
```

5. deploy to server using "mvn clean install -Padobe-public,autoInstallSinglePackage"

The package installation will fail due to the error in the install hook. When using a separate package for the accesscontrol install hook (instead of using the "all" package), that package will fail only during the initial installation. For all following installations it will work, since it seems the class biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook is properly loaded until then. Also, when using a separate package for the install hook, that package can be installed manually in the package manager without errors.

**Comment by ghenzler** [comment]
@aderler IIRC there was a problem installing it into /apps, try using [subPackage](http://jackrabbit.apache.org/filevault-package-maven-plugin/generate-metadata-mojo.html#subPackages) (and leaving it in /etc for now) 

@kwin Haven't you had the problem before?

**Comment by aderler** [comment]
@ghenzler we have a working state when using [subPackage](http://jackrabbit.apache.org/filevault-package-maven-plugin/generate-metadata-mojo.html#subPackages) and installing it as a separate package. However, we want to update our project setup due to occasional errors during package deployment in our current setup when using recent AEMaaCS SDKs. We want to eliminate those issues by being conform with the guidelines in the current [AEMaaCS docs](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html#embeddeds), which states that subPackage should not be used and that all packages should be deployed as a single package using the _all_ package.

**Comment by kwin** [comment]
The original issue installing the ACTool Package via OSGi installer is tracked in #451 and has been fixed meanwhile in newer AEMaaCS versions.

@aderler Your set up cannot work, as the all package is the first thing being installed. If that already requires the ACTool install hook, it will fail. Instead use the following setup
1. "actool package"
2. "acl package", leveraging installhook from actool, has an explicit package dependency on 1.
3. "all package", embeds both 1. and 2.

That setup should work fine.

**Comment by kwin** [comment]
This is related to #561. The only known workaround is to switch to /etc/packages from /apps/.../install

**Comment by aderler** [comment]
@kwin Thanks a lot for your help, we were able to solve this issue by doing exactly what you suggested.
Before finding the working solution, we tried using a separate package that has the actool as a subpackage, but, since the parent package was installed to /apps/../install, it didn't work. When including the actool as a subpackage of the all package it works as expected.

**Comment by ghenzler** [comment]
Created #606 to improve the documentation

**Comment by ghenzler** [comment]
See https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Installation.md for updated documentation.
