### ISSUE TITLE
Allow combining EL expression with interpolated values

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#551]
Currently a statement like 

```
- IF [${$[env:MY_VARIABLE;default='default'] ne ''}]
```

leads to the exception

```
Caused by: javax.el.ELException: Failed to parse the expression [${$[env:MY_VARIABLE;default='default'] ne ''}]
	at org.apache.el.lang.ExpressionBuilder.createNodeInternal(ExpressionBuilder.java:148)
	at org.apache.el.lang.ExpressionBuilder.build(ExpressionBuilder.java:178)
	at org.apache.el.lang.ExpressionBuilder.createValueExpression(ExpressionBuilder.java:242)
	at org.apache.el.ExpressionFactoryImpl.createValueExpression(ExpressionFactoryImpl.java:67)
	at biz.netcentric.cq.tools.actool.configreader.YamlMacroElEvaluator.evaluateEl(YamlMacroElEvaluator.java:102) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.configreader.YamlMacroProcessorImpl.evaluateIfStatement(YamlMacroProcessorImpl.java:241) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.configreader.YamlMacroProcessorImpl.transform(YamlMacroProcessorImpl.java:142) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.configreader.YamlMacroProcessorImpl.transform(YamlMacroProcessorImpl.java:122) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.configreader.YamlMacroProcessorImpl.processMacros(YamlMacroProcessorImpl.java:64) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.configreader.YamlConfigurationMerger.getMergedConfigurations(YamlConfigurationMerger.java:134) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:292) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:261) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.7.0]
```

So it seems that interpolation cannot be used inside EL now. We should lift this limitation.

**Comment by kwin** [comment]
The reason for that is that only scalars starting with `$[` are supported (https://github.com/Netcentric/accesscontroltool/blob/6a09a6fb23715536ae7995f3c29e4ee0a788c6ea/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configreader/YamlConfigurationMerger.java#L107)
