### ISSUE TITLE
NPE in AuthInstallerUserManagerPrefetchingImpl in AEMCloud with incomplete/invalid search index in place

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#557]
With the most recent 2.7.2-SNAPSHOT I ran into the following exception

```
*INFO* [qtp9431062-822-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthInstallerUserManagerPrefetchingImpl Prefetched 1 authorizables in 15ms
...
*ERROR* [qtp9431062-822] biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook Exception during execution of install hook: biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.NullPointerException
...
Caused by: biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.NullPointerException
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAuthorizables(AcInstallationServiceImpl.java:564)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAcConfiguration(AcInstallationServiceImpl.java:343)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installMergedConfigurations(AcInstallationServiceImpl.java:668)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:304)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:270)
	at biz.netcentric.cq.tools.actool.installhook.impl.AcToolInstallHookServiceImpl.installYamlFilesFromPackage(AcToolInstallHookServiceImpl.java:63)
	at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.install(AcToolInstallHook.java:99)
	... 73 common frames omitted
Caused by: java.lang.NullPointerException: null
	at biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthInstallerUserManagerPrefetchingImpl.<init>(AuthInstallerUserManagerPrefetchingImpl.java:94)
	at biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl.installAuthorizables(AuthorizableInstallerServiceImpl.java:114)
	at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAuthorizables(AcInstallationServiceImpl.java:551)
	... 79 common frames omitted

```

**Comment by kwin** [comment]
In my case the `nonRegularUserMembersByAuthorizableId` was populated with only user id `anonymous`. That user was found as member in group `fragment-everyone`. As that group id was not contained in the `nonRegularUserMembersByAuthorizableId` the code in line 94: `nonRegularUserMembersByAuthorizableId.get(memberOfGroupId)` returns `null`, leading to the NPE as the `add` is unconditionally called on the return value.

**Comment by kwin** [comment]
Setting log `org.apache.jackrabbit.oak.query.QueryImpl` to DEBUG (https://helpx.adobe.com/experience-manager/kb/oak-jcr-query-analysis.html) exposed

```
02.02.2021 17:51:19.306 *DEBUG* [qtp9431062-1268-ACTool-Config-Worker] org.apache.jackrabbit.oak.query.QueryImpl cost using filter Filter(query=select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [jcr:primaryType] <> 'rep:User' union select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [rep:authorizableId] = 'anonymous' /* xpath: /jcr:root/home//element(*,rep:Authorizable)[(@jcr:primaryType!='rep:User' or @rep:authorizableId='anonymous')] */, path=/home//*, property=[rep:authorizableId=[anonymous]])
02.02.2021 17:51:19.306 *DEBUG* [qtp9431062-1268-ACTool-Config-Worker] org.apache.jackrabbit.oak.query.QueryImpl cost for reference is Infinity
02.02.2021 17:51:19.306 *DEBUG* [qtp9431062-1268-ACTool-Config-Worker] org.apache.jackrabbit.oak.query.QueryImpl cost for property is 2.0
02.02.2021 17:51:19.306 *DEBUG* [qtp9431062-1268-ACTool-Config-Worker] org.apache.jackrabbit.oak.query.QueryImpl cost for traverse is 2000.0
02.02.2021 17:51:19.306 *DEBUG* [qtp9431062-1268-ACTool-Config-Worker] org.apache.jackrabbit.oak.query.QueryImpl query execute select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [jcr:primaryType] <> 'rep:User' union select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [rep:authorizableId] = 'anonymous' /* xpath: /jcr:root/home//element(*,rep:Authorizable)[(@jcr:primaryType!='rep:User' or @rep:authorizableId='anonymous')] */
```

Also manually executing XPath query `/jcr:root/home//element(*,rep:Authorizable)[(@jcr:primaryType!='rep:User' or @rep:authorizableId='anonymous')]`only exposed one single result (i.e. the anonymous user)
![Screenshot 2021-02-02 at 17 59 16](https://user-images.githubusercontent.com/185025/106634778-66368380-6580-11eb-847f-69e1d7687ff3.png)

This happens for me on AEM Cloud SDK Quickstart version 2021.1.4738.20210107T143101Z 

So it seems just an unsuitable property index (not sure which one) is used for executing the query which does not contain any groups.

**Comment by kwin** [comment]
With a more simplified search ( `/jcr:root/home//element(*,rep:Authorizable)`) another index is chosen but this returns 0 results:

```
02.02.2021 18:11:33.015 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost using filter Filter(query=select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') /* xpath: /jcr:root/home//element(*,rep:Authorizable) */, path=/home//*)
02.02.2021 18:11:33.015 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for reference is Infinity
02.02.2021 18:11:33.015 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for property is Infinity
02.02.2021 18:11:33.015 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for nodeType is 94.0
02.02.2021 18:11:33.032 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for [/oak:index/authorizables] of type (lucene-property) with plan [lucene:authorizables(/oak:index/authorizables) :ancestors:/home] is 258,00
02.02.2021 18:11:33.032 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for [/oak:index/aecuHistory] of type (lucene-property) with plan [lucene:aecuHistory(/oak:index/aecuHistory) :ancestors:/home] is 32,00
02.02.2021 18:11:33.032 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for lucene-property is Infinity
02.02.2021 18:11:33.032 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for aggregate lucene is Infinity
02.02.2021 18:11:33.033 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for aggregate solr is Infinity
02.02.2021 18:11:33.033 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl cost for traverse is 2000.0
02.02.2021 18:11:33.033 *DEBUG* [qtp9431062-1267] org.apache.jackrabbit.oak.query.QueryImpl query execute select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') /* xpath: /jcr:root/home//element(*,rep:Authorizable) */
```

Once I removed that broken index (`/oak:index/aecuHistory`, https://github.com/valtech/aem-easy-content-upgrade/blob/bcf26007964a1982a724df1aab3a470c964ee1c1/ui.apps/src/main/content/jcr_root/_oak_index/aecuHistory/.content.xml) the query returns groups as well!
The custom index was broken due to a typo in a property name: https://github.com/valtech/aem-easy-content-upgrade/pull/150/commits/77ae86d3da6d9af382c73b323edf1bd56ba26632.

Without the custom index the following index is being picked
```
02.02.2021 18:29:55.233 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost using filter Filter(query=select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [jcr:primaryType] <> 'rep:User' union select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [rep:authorizableId] = 'anonymous' /* xpath: /jcr:root/home//element(*,rep:Authorizable)[(@jcr:primaryType!='rep:User' or @rep:authorizableId='anonymous')] */, path=/home//*, property=[jcr:primaryType=[is not null]])
02.02.2021 18:29:55.233 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for reference is Infinity
02.02.2021 18:29:55.233 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for property is 1602.0
02.02.2021 18:29:55.233 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for nodeType is 94.0
02.02.2021 18:29:55.250 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for [/oak:index/authorizables] of type (lucene-property) with plan [lucene:authorizables(/oak:index/authorizables) :ancestors:/home] is 258,00
02.02.2021 18:29:55.250 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for lucene-property is Infinity
02.02.2021 18:29:55.250 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for aggregate lucene is Infinity
02.02.2021 18:29:55.250 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for aggregate solr is Infinity
02.02.2021 18:29:55.250 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost for traverse is 2000.0
02.02.2021 18:29:55.250 *DEBUG* [qtp9431062-1250] org.apache.jackrabbit.oak.query.QueryImpl cost using filter Filter(query=select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [jcr:primaryType] <> 'rep:User' union select [jcr:path], [jcr:score], * from [rep:Authorizable] as a where isdescendantnode(a, '/home') and [rep:authorizableId] = 'anonymous' /* xpath: /jcr:root/home//element(*,rep:Authorizable)[(@jcr:primaryType!='rep:User' or @rep:authorizableId='anonymous')] */, path=/home//*, property=[rep:authorizableId=[anonymous]])
```
