### ISSUE TITLE
Renaming group with member results in "underlying tree has been disconnected"

### ISSUE THREAD

**Issue by jgorgolewski** [Netcentric/accesscontroltool#562]
Since version 2.7.1 installations that try to rename group using migrateFrom feature fail with following error:
```
Migrating from group old-group-name to new-group-name
- Deleted group old-group-name
E Could not process yaml files (biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.IllegalStateException: Authorizable old-group-name: underlying tree has been disconnected.)
Exception while installing configurations: biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.IllegalStateException: Authorizable old-group-name: underlying tree has been disconnected. 
```
The issue happens when renamed group has member managed by actool. For example, when moving from this configuration:
```
-
  group_config:
    -
      old-group-name:
        -
          name: old-group-name
    -
      group-name-approvers:
        -
          name: group-name-approvers
          isMemberOf: old-group-name
```
to this configuration:
```
-
  group_config:
    -
      new-group-name:
        -
          name: new-group-name
          migrateFrom: old-group-name
    -
      group-name-approvers:
        -
          name: group-name-approvers
          isMemberOf: new-group-name
```

Issue seems to be similar to #542 (side effect of #534) but happens also on 2.7.2. Likely related to  AuthInstallerUserManagerPrefetchingImpl is not clearing caches when authorizables are removed.

Following details are present in the logs:
```
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl - start installation of authorizable: new-group-name
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl start adding new-group-name to assignedGroups
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Successfully created new group: new-group-name
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Migrating from group old-group-name to new-group-name
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl - Deleted group old-group-name
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl - start installation of authorizable: group-name-approvers
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Authorizable group-name-approvers isMemberOf(repo)=[old-group-name]
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Authorizable group-name-approvers isMemberOf(config)=[new-group-name]
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Authorizable group-name-approvers remains member of groups []
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Authorizable group-name-approvers will be added as member of [new-group-name]
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Authorizable group-name-approvers will be removed from members of [old-group-name]
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Membership Change: Adding group-name-approvers to members of group new-group-name in repository
biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl Membership Change: Removing group-name-approvers from members of group old-group-name in repository
biz.netcentric.cq.tools.actool.history.impl.HistoryUtils create node: history_1615036327557_via_installhook
biz.netcentric.cq.tools.actool.history.impl.HistoryUtils delete obsolete history node:
biz.netcentric.cq.tools.actool.history.impl.HistoryUtils Saved history in node: /var/statistics/achistory/history_1615036327557_via_installhook
biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook Exception during execution of install hook: biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.IllegalStateException: Authorizable old-group-name: underlying tree has been disconnected.
biz.netcentric.cq.tools.actool.authorizableinstaller.AuthorizableCreatorException: java.lang.IllegalStateException: Authorizable old-group-name: underlying tree has been disconnected.
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAuthorizables(AcInstallationServiceImpl.java:564)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAcConfiguration(AcInstallationServiceImpl.java:343)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installMergedConfigurations(AcInstallationServiceImpl.java:668)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:304)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installConfigurationFiles(AcInstallationServiceImpl.java:270)
        at biz.netcentric.cq.tools.actool.installhook.impl.AcToolInstallHookServiceImpl.installYamlFilesFromPackage(AcToolInstallHookServiceImpl.java:63)
        at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.install(AcToolInstallHook.java:99)
        at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.execute(AcToolInstallHook.java:42)
(...)
Caused by: java.lang.IllegalStateException: Authorizable old-group-name: underlying tree has been disconnected.
        at org.apache.jackrabbit.oak.security.user.AuthorizableImpl.getTree(AuthorizableImpl.java:188)
        at org.apache.jackrabbit.oak.security.user.GroupImpl.removeMember(GroupImpl.java:152)
        at org.apache.jackrabbit.oak.jcr.delegate.GroupDelegator$7.perform(GroupDelegator.java:157)
        at org.apache.jackrabbit.oak.jcr.delegate.GroupDelegator$7.perform(GroupDelegator.java:153)
        at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:207)
        at org.apache.jackrabbit.oak.jcr.delegate.GroupDelegator.removeMember(GroupDelegator.java:153)
        at biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl.applyGroupMembershipConfigIsMemberOf(AuthorizableInstallerServiceImpl.java:628)
        at biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl.applyGroupMembershipConfigIsMemberOf(AuthorizableInstallerServiceImpl.java:514)
        at biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl.installAuthorizableConfigurationBean(AuthorizableInstallerServiceImpl.java:170)
        at biz.netcentric.cq.tools.actool.authorizableinstaller.impl.AuthorizableInstallerServiceImpl.installAuthorizables(AuthorizableInstallerServiceImpl.java:119)
        at biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl.installAuthorizables(AcInstallationServiceImpl.java:551)
        ... 70 common frames omitted
```

**Comment by tomasalmeida** [comment]
Hi @jgorgolewski can you post one example how to reproduce the issue?

**Comment by jgorgolewski** [comment]
Hi @tomasalmeida, are you able to reproduce it?

**Comment by tomasalmeida** [comment]
Hi @jgorgolewski, I will try to reproduce it and post the result.
