### ISSUE TITLE
accesscontroltool-content-package-2.7.2.zip blocks content distribution queue in AEMaaCS

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#566]
The deployment fails and the following error can be observed in the publish logs:

```
15.03.2021 17:35:22.248 [cm-p29008-e106842-aem-publish-7c69f78f56-rb9wv] *INFO* [Queue Processor for Subscriber agent publishSubscriber] org.apache.sling.distribution.journal.bookkeeper.ContentPackageExtractor Content package received at /etc/packages/Netcentric/accesscontroltool-content-package-2.7.2.zip. Starting import.
15.03.2021 17:35:22.293 [cm-p29008-e106842-aem-publish-7c69f78f56-rb9wv] *ERROR* [Queue Processor for Subscriber agent publishSubscriber] org.apache.jackrabbit.vault.fs.impl.io.GenericArtifactHandler Error while parsing /jcr_root/_rep_policy.xml: {}
org.xml.sax.SAXException: javax.jcr.AccessDeniedException: Access denied.
	at org.apache.jackrabbit.vault.fs.impl.io.DocViewSAXImporter.endElement(DocViewSAXImporter.java:1245) [org.apache.jackrabbit.vault:3.4.0]
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
	at org.apache.jackrabbit.vault.fs.impl.io.GenericArtifactHandler.accept(GenericArtifactHandler.java:100) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:896) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:799) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:839) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.io.Importer.run(Importer.java:440) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:232) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:401) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:360) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:346) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.sling.distribution.journal.bookkeeper.ContentPackageExtractor.installPackage(ContentPackageExtractor.java:101) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.bookkeeper.ContentPackageExtractor.installPackage(ContentPackageExtractor.java:93) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.bookkeeper.ContentPackageExtractor.handle(ContentPackageExtractor.java:72) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.bookkeeper.PackageHandler.installAddPackage(PackageHandler.java:79) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.bookkeeper.PackageHandler.apply(PackageHandler.java:61) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.bookkeeper.BookKeeper.importPackage(BookKeeper.java:148) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.impl.subscriber.DistributionSubscriber.processQueueItem(DistributionSubscriber.java:339) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.impl.subscriber.DistributionSubscriber.fetchAndProcessQueueItem(DistributionSubscriber.java:296) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at org.apache.sling.distribution.journal.impl.subscriber.DistributionSubscriber.processQueue(DistributionSubscriber.java:275) [org.apache.sling.distribution.journal:0.2.0.T202009251421-0284693]
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.jcr.AccessDeniedException: Access denied.
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.checkPermissions(AbstractAccessControlManager.java:208) [org.apache.jackrabbit.oak-security-spi:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.getTree(AbstractAccessControlManager.java:168) [org.apache.jackrabbit.oak-security-spi:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.spi.security.authorization.principalbased.impl.PrincipalBasedAccessControlManager.getPolicies(PrincipalBasedAccessControlManager.java:161) [org.apache.jackrabbit.oak-authorization-principalbased:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.security.authorization.composite.CompositeAccessControlManager.getPolicies(CompositeAccessControlManager.java:82) [org.apache.jackrabbit.oak-core:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator$5.perform(AccessControlManagerDelegator.java:97) [org.apache.jackrabbit.oak-jcr:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator$5.perform(AccessControlManagerDelegator.java:93) [org.apache.jackrabbit.oak-jcr:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:209) [org.apache.jackrabbit.oak-jcr:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator.getPolicies(AccessControlManagerDelegator.java:93) [org.apache.jackrabbit.oak-jcr:1.37.0.R1885266]
	at org.apache.jackrabbit.oak.jcr.delegate.JackrabbitAccessControlManagerDelegator.getPolicies(JackrabbitAccessControlManagerDelegator.java:141) [org.apache.jackrabbit.oak-jcr:1.37.0.R1885266]
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter$ImportedPolicy.getPolicy(JackrabbitACLImporter.java:182) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter$ImportedAcList.apply(JackrabbitACLImporter.java:267) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter.close(JackrabbitACLImporter.java:154) [org.apache.jackrabbit.vault:3.4.0]
	at org.apache.jackrabbit.vault.fs.impl.io.DocViewSAXImporter.endElement(DocViewSAXImporter.java:1189) [org.apache.jackrabbit.vault:3.4.0]
	... 31 common frames omitted

```

**Comment by kwin** [comment]
The problem is this ACL: https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-content-package/src/main/jcr_root/_rep_policy.xml. The problem is described at https://experienceleague.adobe.com/docs/experience-manager-learn/cloud-service/debugging/debugging-aem-as-a-cloud-service/build-and-deployment.html?lang=en#deploy-to. The service user on the publish does not have the right to apply ACLs to root level.

The service user's rights can be seen in https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2021.3.5026.20210309T210727Z-210225/aem-sdk-api-2021.3.5026.20210309T210727Z-210225-aem-publish-sdk.slingosgifeature:

```
  "# GRANITE-23007 - [RTC] Configure service user mapping for Pipeline replication",
    "create service user sling-distribution-importer with forced path system/cq:services/internal",
    "set principal ACL for sling-distribution-importer",
    "  allow jcr:modifyAccessControl,jcr:readAccessControl on /content",
    "  allow jcr:modifyAccessControl,jcr:readAccessControl on /conf",
    "  allow jcr:modifyAccessControl,jcr:readAccessControl on /etc",
    "  allow jcr:nodeTypeDefinitionManagement,rep:privilegeManagement on :repository ",
    "end",
```

**Comment by kwin** [comment]
I don't know of any other backwards-compatible fix except for relying on an already existing service user which has the correct privileges (i.e. read only on everything).

**Comment by kwin** [comment]
Probably the easiest is to create two different packages already (similar to what we do for the custom oak index). One for AEMaaCS relying on repoinit and one for AEM Classic (still relying on rep:policy and repo:policy nodes).
