### ISSUE TITLE
AEMaaCS deployment of AC Tool fails with newest version

### ISSUE THREAD

**Issue by phornig** [Netcentric/accesscontroltool#578]
Hello,

with version 2021.5.5309.20210515T190734Z of AEMaaCS the deployment of AC Tool fails in the "Build Images" phase of the cloud manager pipeline. There is an error in the install hook which causes the instance to shutdown.

Build log excerpt:
```[main] INFO com.adobe.granite.composite.init.LogTail - Extracting package Netcentric:accesscontroltool-apps-package:2.8.1-cp2fm-converted
[main] INFO com.adobe.granite.composite.init.LogTail - Extracting package Netcentric:accesscontroltool-oakindex-package:2.8.1-cp2fm-converted
27.05.2021 08:58:22.707 *INFO* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Loading Hook actool: Main-Class = biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook
27.05.2021 08:58:22.732 *INFO* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook actool registered.
27.05.2021 08:58:22.737 *INFO* [Apache Sling Repository Startup Thread #1] biz.netcentric.cq.tools.actool.installhook.impl.OsgiAwareInstallHook Installing ACLs through AcToolInstallHook in phase PREPARE...
27.05.2021 08:58:22.737 *WARN* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl Hook actool threw package exception. PREPARE aborted.
org.apache.jackrabbit.vault.packaging.PackageException: Could not get AceService from OSGI service registry. Make sure the ACTool is installed!
  at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.install(AcToolInstallHook.java:87) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.8.1]
  at biz.netcentric.cq.tools.actool.installhook.AcToolInstallHook.execute(AcToolInstallHook.java:42) [biz.netcentric.cq.tools.accesscontroltool.bundle:2.8.1]
  at org.apache.jackrabbit.vault.packaging.impl.InstallHookProcessorImpl.execute(InstallHookProcessorImpl.java:143) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:226) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:151) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.registry.impl.FSPackageRegistry.installPackage(FSPackageRegistry.java:712) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.registry.impl.PackageTaskImpl.doInstall(PackageTaskImpl.java:179) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.registry.impl.PackageTaskImpl.execute(PackageTaskImpl.java:109) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanImpl.execute(ExecutionPlanImpl.java:129) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanBuilderImpl.execute(ExecutionPlanBuilderImpl.java:335) [org.apache.jackrabbit.vault:3.4.0]
  at org.apache.sling.jcr.packageinit.impl.ExecutionPlanRepoInitializer.processRepository(ExecutionPlanRepoInitializer.java:165) [org.apache.sling.jcr.packageinit:1.0.2]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.executeRepositoryInitializers(AbstractSlingRepositoryManager.java:610) [org.apache.sling.jcr.base:3.1.6]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.initializeAndRegisterRepositoryService(AbstractSlingRepositoryManager.java:558) [org.apache.sling.jcr.base:3.1.6]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.access$300(AbstractSlingRepositoryManager.java:92) [org.apache.sling.jcr.base:3.1.6]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager$4.run(AbstractSlingRepositoryManager.java:527) [org.apache.sling.jcr.base:3.1.6]
27.05.2021 08:58:22.738 *INFO* [Apache Sling Repository Startup Thread #1] org.apache.jackrabbit.vault.packaging.registry.impl.PackageTaskImpl error during package task EXTRACT on Ab:aem-ab-platform-cloud.permissions:1.0.0-SNAPSHOT-cp2fm-converted: org.apache.jackrabbit.vault.packaging.PackageException: Error while executing an install hook during prepare phase.
[main] INFO com.adobe.granite.composite.init.LogTail - Extracting package day/cq60/product:commerce-addon-configuration:2021.04.22
[main] INFO com.adobe.granite.composite.init.LogTail - Extracting package qewr/division:aem-asdf-divisional.ui.apps:1.0.0-SNAPSHOT-cp2fm-converted
[main] INFO com.adobe.granite.composite.init.LogTail - Extracting package adsf/division:aem-qwer-divisional.ui.apps:1.0.0-SNAPSHOT-cp2fm-converted
[main] INFO com.adobe.granite.composite.init.LogTail - Extracting package Ab:aem-ab-platform-cloud.ui.config:1.0.0-SNAPSHOT-cp2fm-converted
27.05.2021 08:58:23.825 *ERROR* [Apache Sling Repository Startup Thread #1] com.adobe.granite.repository.impl.SlingRepositoryManager Exception in a SlingRepositoryInitializer, SlingRepository service registration aborted
java.lang.IllegalStateException: Excecutionplan execution contained errors - cannot complete repository initialization.
  at org.apache.sling.jcr.packageinit.impl.ExecutionPlanRepoInitializer.processRepository(ExecutionPlanRepoInitializer.java:168) [org.apache.sling.jcr.packageinit:1.0.2]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.executeRepositoryInitializers(AbstractSlingRepositoryManager.java:610) [org.apache.sling.jcr.base:3.1.6]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.initializeAndRegisterRepositoryService(AbstractSlingRepositoryManager.java:558) [org.apache.sling.jcr.base:3.1.6]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager.access$300(AbstractSlingRepositoryManager.java:92) [org.apache.sling.jcr.base:3.1.6]
  at org.apache.sling.jcr.base.AbstractSlingRepositoryManager$4.run(AbstractSlingRepositoryManager.java:527) [org.apache.sling.jcr.base:3.1.6]
  Suppressed: org.apache.jackrabbit.vault.packaging.PackageException: Error while executing an install hook during prepare phase.
    at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:229) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:151) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.jackrabbit.vault.packaging.registry.impl.FSPackageRegistry.installPackage(FSPackageRegistry.java:712) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.jackrabbit.vault.packaging.registry.impl.PackageTaskImpl.doInstall(PackageTaskImpl.java:179) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.jackrabbit.vault.packaging.registry.impl.PackageTaskImpl.execute(PackageTaskImpl.java:109) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanImpl.execute(ExecutionPlanImpl.java:129) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.jackrabbit.vault.packaging.registry.impl.ExecutionPlanBuilderImpl.execute(ExecutionPlanBuilderImpl.java:335) [org.apache.jackrabbit.vault:3.4.0]
    at org.apache.sling.jcr.packageinit.impl.ExecutionPlanRepoInitializer.processRepository(ExecutionPlanRepoInitializer.java:165) [org.apache.sling.jcr.packageinit:1.0.2]
    ... 4 common frames omitted
27.05.2021 08:58:23.826 *INFO* [Apache Sling Repository Startup Thread #1] com.adobe.granite.repository.impl.SlingRepositoryManager Stop requested
27.05.2021 08:58:23.831 *INFO* [Apache Sling Repository Startup Thread #1] com.adobe.granite.repository.impl.SlingRepositoryManager stop: Repository still running, forcing shutdown```

**Comment by kwin** [comment]
This is due to the fact that `actool.forceInstallHookInCloud` was set to true in the package properties and https://issues.apache.org/jira/browse/SLING-10205 is now live on the Cloud Manager for AEMaaCS. That leads to fact that the install hook is executed during calling a repository initializer. As this is quite early during the start most of the services (at least all the ones which depend on `SlingService`, like https://github.com/Netcentric/accesscontroltool/blob/2f1d9fe233643ad76530f87127d722c2984ea791/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/AcInstallationServiceImpl.java#L110) are not yet started. I propose to get rid of the property `actool.forceInstallHookInCloud` and stop evaluating this in https://github.com/Netcentric/accesscontroltool/blob/2f1d9fe233643ad76530f87127d722c2984ea791/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/installhook/AcToolInstallHook.java#L77.

Once you remove setting `actool.forceInstallHookInCloud` it should start working again with the newest AEMaaCS.

**Comment by phornig** [comment]
I can confirm that this was the problem and removing the `actool.forceInstallHookInCloud` setting fixes the issue.

Thanks!

**Comment by kwin** [comment]
The flag `actool.forceInstallHookInCloud` has been removed since version 3.0.0
