### ISSUE TITLE
ACTool Configuration fails to create users/groups in AEMaaCS

### ISSUE THREAD

**Issue by sparktronics** [Netcentric/accesscontroltool#620]
We are seeing that in a AEMaaCS instance, when the actool is executed, although the error log shows that the groups have been crated, at the end of the failed execution, no groups are persisted. We see a document store exception.

The actool seems to startup correctly. It logs the creation of users but when it tries to save them, the DocumentStoreException is triggered.

Then a token ImsExchangeTokenException is thrown (which I have no idea what type of exception could be happening and is also level INFO)

```
16.11.2021 01:12:52.505 [cm-p30502-e190707-aem-author-67dc89c6df-vxg7w] *INFO* [sling-default-4-Register
ed Service.163] com.adobe.granite.toggle.impl.ToggleRouterImpl A suppressed exception occurred, ignore.
com.adobe.granite.toggle.sdk.exceptions.ImsExchangeTokenException: Connection pool shut down
```

And then the document store 

```
16.11.2021 01:12:52.775 [cm-p30502-e190707-aem-author-67dc89c6df-8jp65] *WARN* [DocumentNodeStore lease update thread (3)] org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore BackgroundLeaseUpdate.execute: time since last renewClusterIdLease() call longer than expected: 4842ms (expected ~1000ms)
```

Other errors are also produced during the saving of the history of executions

```
16.11.2021 01:09:58.401 [cm-p30502-e190707-aem-author-67dc89c6df-8jp65] *ERROR* [Apache Sling Repository
 Startup Thread #1-ACTool-Config-Worker] biz.netcentric.cq.tools.actool.history.impl.AcHistoryServiceImp
l Could not persist history: org.apache.jackrabbit.oak.plugins.document.DocumentStoreException: This oak
 instance failed to update the lease in time and can therefore no longer access this DocumentNodeStore.
(since 2021-11-15T23:54:15.258Z)
at org.apache.jackrabbit.oak.plugins.document.ClusterNodeInfo.leaseExpired(ClusterNodeInfo.java:
1292) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
at org.apache.jackrabbit.oak.plugins.document.ClusterNodeInfo.performLeaseCheck(ClusterNodeInfo.
java:747) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.util.LeaseCheckDocumentStoreWrapper.performLeaseCh
eck(LeaseCheckDocumentStoreWrapper.java:56) [org.apache.jackrabbit.oak-store-document:1.40.0.T2021101910
0256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.util.LeaseCheckDocumentStoreWrapper.find(LeaseChec
kDocumentStoreWrapper.java:62) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore.readNode(DocumentNodeStore.java:
1496) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore.access$1100(DocumentNodeStore.ja
va:135) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore$6.call(DocumentNodeStore.java:12
78) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore$6.call(DocumentNodeStore.java:12
71) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.load(CacheLIRS.java:1027)
        at org.apache.jackrabbit.oak.cache.CacheLIRS$Segment.get(CacheLIRS.java:988)
        at org.apache.jackrabbit.oak.cache.CacheLIRS.get(CacheLIRS.java:299)
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeStore.getNode(DocumentNodeStore.java:1271) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeState.getChildNodeDoc(DocumentNodeState.java:520) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeState.getChildNode(DocumentNodeState.j:
 
at org.apache.jackrabbit.oak.plugins.memory.MemoryNodeBuilder.<init>(MemoryNodeBuilder.java:142) [org.apache.jackrabbit.oak-store-spi:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.AbstractDocumentNodeBuilder.<init>(AbstractDocumentNodeBuilder.java:41) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentNodeBuilder.<init>(DocumentNodeBuilder.java:46) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.DocumentRootBuilder.createChildBuilder(DocumentRootBuilder.java:99) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.AbstractDocumentNodeBuilder.getChildNode(AbstractDocumentNodeBuilder.java:73) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.plugins.document.AbstractDocumentNodeBuilder.getChildNode(AbstractDocumentNodeBuilder.java:33) [org.apache.jackrabbit.oak-store-document:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.composite.CompositeNodeBuilder.lambda$getChildNode$6(CompositeNodeBuilder.java:222) [org.apache.jackrabbit.oak-store-composite:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.composite.NodeMap.lambda$curry$3(NodeMap.java:65) [org.apache.jackrabbit.oak-store-composite:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.composite.NodeMap$CacheableSupplier.lambda$lazyApply$0(NodeMap.java:111) [org.apache.jackrabbit.oak-store-composite:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.composite.NodeMap$CacheableSupplier.get(NodeMap.java:98) [org.apache.jackrabbit.oak-store-composite:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.composite.NodeMap.get(NodeMap.java:49) [org.apache.jackrabbit.oak-store-composite:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.composite.CompositeNodeBuilder.getChildNode(CompositeNodeBuilder.ja:
at org.apache.jackrabbit.oak.core.SecureNodeBuilder.<init>(SecureNodeBuilder.java:111) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.core.SecureNodeBuilder.getChildNode(SecureNodeBuilder.java:328) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.core.MutableTree.getTree(MutableTree.java:288) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.core.MutableRoot.getTree(MutableRoot.java:222) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.core.MutableRoot.getTree(MutableRoot.java:71) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.namepath.impl.GlobalNameMapper.init(GlobalNameMapper.java:91) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.namepath.impl.GlobalNameMapper.<init>(GlobalNameMapper.java:82) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.namepath.impl.LocalNameMapper.<init>(LocalNameMapper.java:36) [org.apache.jackrabbit.oak-core:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.jcr.session.SessionNamespaces.<init>(SessionNamespaces.java:46) [org.apache.jackrabbit.oak-jcr:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.<init>(SessionDelegate.java:143) [org.apache.jackrabbit.oak-jcr:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.jcr.repository.RepositoryImpl$1.<init>(RepositoryImpl.java:320) [org.apache.jackrabbit.oak-jcr:1.40.0.T20211019100256-95777e8]
        at org.apache.jackrabbit.oak.jcr.repository.RepositoryImpl.createSessionDelegate(RepositoryImpl.java:318) [org.apache.jackrabbit.oak-jcr:1.40.0.T20211019100256-95777e8]
```

**Comment by ghenzler** [comment]
Most likely the root cause is a long-running execution on mutable content - the approach from #618 should fix it

**Comment by ghenzler** [comment]
As #618 fixed it we should make this the default to avoid other projects run into it. I created #622 for it
