### ISSUE TITLE
IllegalStateException when deploying in the cloud

### ISSUE THREAD

**Issue by pawee-del** [Netcentric/accesscontroltool#631]
Hi I am getting this error when deploying in the cloud :

`91mjava.lang.IllegalStateException: Error while assembling launcher: Package has unresolved dependencies: Netcentric:accesscontroltool-package:3.0.4,
[0m[91m	at org.apache.sling.feature.launcher.impl.Bootstrap.runWithException(Bootstrap.java:169)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.PrepareContentCommand.doCall(PrepareContentCommand.java:120)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.AbstractRepoCommand.call(AbstractRepoCommand.java:67)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.BuildImageCommand.doContent(BuildImageCommand.java:760)[0m[91m
[0m[91m	at com.adobe.granite.fact.command.BuildImageCommand$2.run(BuildImageCommand.java:1034)`

it deploys fine on local, and in the cloud , it failed when building the images :

<img width="419" alt="2022-05-17 09_43_10-Pipeline Execution _ Cloud Manager — Mozilla Firefox" src="https://user-images.githubusercontent.com/72118587/168699686-b3af1b1a-0327-46f4-93eb-21ec7037e1ce.png">

**Comment by kwin** [comment]
You need to paste the complete build log, otherwise it is impossible to tell what went wrong. Also please share the AEM version you are trying to deploy to.
