### ISSUE TITLE
QueryHelperIT.testHasQueryIndexForACLsWithIndex sometimes fails

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#755]
During the CI build the QueryHelperIT sometimes fails.
It emits then

```
[INFO] Running biz.netcentric.cq.tools.actool.helper.QueryHelperIT
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Found a new index node [reference]. Reindexing is requested
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing will be performed for following indexes: [/oak:index/uuid, /oak:index/reference, /oak:index/nodetype]
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Indexing report
    - /oak:index/uuid*(0)
    - /oak:index/reference*(0)
    - /oak:index/nodetype*(1252)

[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing completed
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing will be performed for following indexes: [/oak:index/principalName, /oak:index/authorizableId, /oak:index/acPrincipalName, /oak:index/repMembers]
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Indexing report
    - /oak:index/principalName*(2)
    - /oak:index/authorizableId*(2)
    - /oak:index/acPrincipalName*(0)
    - /oak:index/repMembers*(0)

[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing completed
[main] INFO biz.netcentric.cq.tools.actool.extensions.OakRepository - repository created: Apache Jackrabbit Oak 1.48.0
[main] WARN org.apache.jackrabbit.oak.query.QueryImpl - Traversal query (query without index): EXPLAIN MEASURE SELECT * FROM [rep:ACL] AS s WHERE ISDESCENDANTNODE([/]); consider creating an index
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.234 s <<< FAILURE! -- in biz.netcentric.cq.tools.actool.helper.QueryHelperIT
Error:  biz.netcentric.cq.tools.actool.helper.QueryHelperIT.testHasQueryIndexForACLsWithIndex(Session) -- Time elapsed: 0.008 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at biz.netcentric.cq.tools.actool.helper.QueryHelperIT.testHasQueryIndexForACLsWithIndex(QueryHelperIT.java:60)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    QueryHelperIT.testHasQueryIndexForACLsWithIndex:60 expected: <true> but was: <false>
```

(e.g. in  https://github.com/Netcentric/accesscontroltool/actions/runs/9959305308/job/27515848789?pr=754).

It is currently unclear under which circumstances this may happen.

**Comment by kwin** [comment]
Failure with increased logging:

```
[INFO] Running biz.netcentric.cq.tools.actool.helper.QueryHelperIT
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Found a new index node [reference]. Reindexing is requested
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing will be performed for following indexes: [/oak:index/uuid, /oak:index/reference, /oak:index/nodetype]
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Indexing report
    - /oak:index/uuid*(0)
    - /oak:index/reference*(0)
    - /oak:index/nodetype*(1252)

[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing completed
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing will be performed for following indexes: [/oak:index/principalName, /oak:index/authorizableId, /oak:index/acPrincipalName, /oak:index/repMembers]
[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Indexing report
    - /oak:index/principalName*(2)
    - /oak:index/authorizableId*(2)
    - /oak:index/acPrincipalName*(0)
    - /oak:index/repMembers*(0)

[main] INFO org.apache.jackrabbit.oak.plugins.index.IndexUpdate - Reindexing completed
[main] INFO biz.netcentric.cq.tools.actool.extensions.OakRepository - repository created: Apache Jackrabbit Oak 1.48.0
[main] WARN org.apache.jackrabbit.oak.query.QueryImpl - Traversal query (query without index): EXPLAIN MEASURE SELECT * FROM [rep:ACL] AS s WHERE ISDESCENDANTNODE([/]); consider creating an index
[main] DEBUG biz.netcentric.cq.tools.actool.helper.QueryHelper - Execution plan and cost for EXPLAIN MEASURE SELECT * FROM [rep:ACL] AS s WHERE ISDESCENDANTNODE([/]): [rep:ACL] as [s] /* traverse "//*" where isdescendantnode([s], [/]) */ cost: { "s": 1.0E8 }
[main] DEBUG biz.netcentric.cq.tools.actool.helper.QueryHelper - Cost for rep:ACL query is estimated with 1.0E8
[main] DEBUG biz.netcentric.cq.tools.actool.helper.QueryHelper - Execution plan and cost for EXPLAIN MEASURE SELECT * FROM [rep:ACL] AS s WHERE ISDESCENDANTNODE([/]): [rep:ACL] as [s] /* nodeType Filter(query=EXPLAIN MEASURE SELECT * FROM [rep:ACL] AS s WHERE ISDESCENDANTNODE([/]), path=//*) where isdescendantnode([s], [/]) */ cost: { "s": 104.0 }
[main] DEBUG biz.netcentric.cq.tools.actool.helper.QueryHelper - Cost for rep:ACL query is estimated with 104.0
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.494 s <<< FAILURE! -- in biz.netcentric.cq.tools.actool.helper.QueryHelperIT
Error:  biz.netcentric.cq.tools.actool.helper.QueryHelperIT.testHasQueryIndexForACLsWithIndex(Session) -- Time elapsed: 0.018 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)
	at biz.netcentric.cq.tools.actool.helper.QueryHelperIT.testHasQueryIndexForACLsWithIndex(QueryHelperIT.java:60)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

For some reason the cost for the index based query is above 100 in this case.

**Comment by kwin** [comment]
The cost for the property index based result may be above 100 because there is some overhead per store strategy: https://github.com/apache/jackrabbit-oak/blob/5da34e80f0c5dc2cffe189e71d39ebd2fb726e6b/oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/property/PropertyIndexLookup.java#L147. The strategy https://github.com/apache/jackrabbit-oak/blob/5da34e80f0c5dc2cffe189e71d39ebd2fb726e6b/oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/property/strategy/UniqueEntryStoreStrategy.java#L223 always adds a number on top. For now let us assume this may add up to 100 on top which leads to a threshold of 200.
